### ISSUE TITLE
Pre-work - Tip Calculator submission

### ISSUE THREAD

**Issue by dunghuynh1990** [dunghuynh1990/TipsCalculator#2]
Here my complete Pre-work - Tip Calculator App.
Please review and give me feedback. Thank you. 
cc @coderschoolreview

**Comment by avo1** [comment]
Hi @dunghuynh1990 ,

Thanks for your submission 👍 It looks good.

### Quick Comments:
- Good usage of `NSUserDefaults`. This is one of the methods to pass the data from multiple viewController. We will learn few more ways to do that. 
- If you were able to save the tipPercentage, why didn't you save the billAmount? (one of the optional). It should be exactly the same.
- It's great you know how to use the tableView and delegate. We'll also cover that in detail during class.
- It's a good practice to validate user's input as you did in the setting page for tip percentages. However, if I just edit the number, for ex - the minimum value, and still let the cursor there, then I tap on back, the `textFieldDidChange` will not be called and nothing happens when you go back. Users will have no idea.

<img width="373" alt="screen shot 2016-06-12 at 12 42 30 pm" src="https://cloud.githubusercontent.com/assets/10482065/15989213/2b7d1dae-309b-11e6-91ec-dbd227fd263a.png">
- You shouldn't let the user enter invalid number, should you? I can enter bunch of leading zeros and decimal points.

<img width="376" alt="screen shot 2016-06-12 at 12 29 42 pm" src="https://cloud.githubusercontent.com/assets/10482065/15989194/d40f3994-309a-11e6-9524-ee7306ff7622.png">

### Optional Suggestions to Improve
- Look into the `UIView.animateWithDuration` functions to add animations.
- It's OK to use `String(format: "$%.2f", tip)` in this case, but if you change the language to Vietnamese for example, we don't use 2 digits after decimal point and the $ sign, right? I recommend to try `NSNumberFormatter` and `CurrencyStyle`. If I change to Vietnamese, it should show `đ 12,000` for example.

I encourage you to try out the optional tasks to increase your chance. Fyi the deadline was extended to June 24.

Regards,
Dave

**Comment by dunghuynh1990** [comment]
Hi @avo1,
Thanks for your review. I will fix those bugs and do the optional tasks.

Regards,
Huynh Tri Dung

**Comment by coderschoolreview** [comment]
Hi Dung, have you done any improvement that you want to update?

**Comment by dunghuynh1990** [comment]
Hi @avo1 , @coderschoolreview 

Here are some improvements:
1. I use Slider for adjustment percentage in Setting screen. So user will use less tap and the there will be no bugs related to input percentage.
2. In Main View: user can not input invalid number (bunch of leading zero)
3. Update `CurrencyStyle` so that if you change your Region to Vietnam, the app will automatically display `đ`.

**Comment by avo1** [comment]
Good fix! We'll email you about the class soon.
